/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateClientInput = {
  id?: string | null,
  user: string,
  name: string,
  lastname: string,
  city: string,
  state: string,
  country: string,
  zip: string,
  phone: string,
  email: string,
};

export type ModelClientConditionInput = {
  user?: ModelStringInput | null,
  name?: ModelStringInput | null,
  lastname?: ModelStringInput | null,
  city?: ModelStringInput | null,
  state?: ModelStringInput | null,
  country?: ModelStringInput | null,
  zip?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  and?: Array< ModelClientConditionInput | null > | null,
  or?: Array< ModelClientConditionInput | null > | null,
  not?: ModelClientConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type Client = {
  __typename: "Client",
  id: string,
  user: string,
  name: string,
  lastname: string,
  city: string,
  state: string,
  country: string,
  zip: string,
  phone: string,
  email: string,
  deliveryAddress?: ModelDeliveryConnection | null,
  orders?: ModelOrderConnection | null,
  createdAt: string,
  updatedAt: string,
  owner?: string | null,
};

export type ModelDeliveryConnection = {
  __typename: "ModelDeliveryConnection",
  items:  Array<Delivery | null >,
  nextToken?: string | null,
};

export type Delivery = {
  __typename: "Delivery",
  id: string,
  city: string,
  state: string,
  country: string,
  zip: string,
  phone: string,
  address: string,
  details?: string | null,
  order?: Order | null,
  client?: Client | null,
  createdAt: string,
  updatedAt: string,
  clientDeliveryAddressId?: string | null,
  deliveryOrderId?: string | null,
  owner?: string | null,
};

export type Order = {
  __typename: "Order",
  id: string,
  title: string,
  date: string,
  total: number,
  orderDetails:  Array<OrderDetail >,
  client?: Client | null,
  delivery?: Delivery | null,
  status: OrderStatus,
  paymentStatus: PaymentStatus,
  paymentType: PaymentType,
  products?: ModelProductOrdersConnection | null,
  createdAt: string,
  updatedAt: string,
  clientOrdersId?: string | null,
  orderDeliveryId?: string | null,
  owner?: string | null,
};

export type OrderDetail = {
  __typename: "OrderDetail",
  productID: string,
  productName: string,
  productColor: string,
  productThumbnail: string,
  quantity: number,
  total: number,
};

export enum OrderStatus {
  received = "received",
  procesing = "procesing",
  delivering = "delivering",
  delivered = "delivered",
  canceled = "canceled",
}


export enum PaymentStatus {
  procesing = "procesing",
  acepted = "acepted",
  rejected = "rejected",
  pending = "pending",
}


export enum PaymentType {
  cash = "cash",
  bankWire = "bankWire",
  creditCard = "creditCard",
  paypal = "paypal",
}


export type ModelProductOrdersConnection = {
  __typename: "ModelProductOrdersConnection",
  items:  Array<ProductOrders | null >,
  nextToken?: string | null,
};

export type ProductOrders = {
  __typename: "ProductOrders",
  id: string,
  productID: string,
  orderID: string,
  product: Product,
  order: Order,
  createdAt: string,
  updatedAt: string,
  owner?: string | null,
};

export type Product = {
  __typename: "Product",
  id: string,
  name: string,
  price: number,
  weight?: number | null,
  options:  Array<ProductOptions >,
  thumbnail: string,
  images: Array< string >,
  description: string,
  avilable: boolean,
  unlimited: boolean,
  extraDetails?: string | null,
  order?: ModelProductOrdersConnection | null,
  createdAt: string,
  updatedAt: string,
  owner?: string | null,
};

export type ProductOptions = {
  __typename: "ProductOptions",
  name: string,
  thumbnail: string,
  colorCode: string,
  stock: number,
};

export type ModelOrderConnection = {
  __typename: "ModelOrderConnection",
  items:  Array<Order | null >,
  nextToken?: string | null,
};

export type UpdateClientInput = {
  id: string,
  user?: string | null,
  name?: string | null,
  lastname?: string | null,
  city?: string | null,
  state?: string | null,
  country?: string | null,
  zip?: string | null,
  phone?: string | null,
  email?: string | null,
};

export type DeleteClientInput = {
  id: string,
};

export type CreateDeliveryInput = {
  id?: string | null,
  city: string,
  state: string,
  country: string,
  zip: string,
  phone: string,
  address: string,
  details?: string | null,
  clientDeliveryAddressId?: string | null,
  deliveryOrderId?: string | null,
};

export type ModelDeliveryConditionInput = {
  city?: ModelStringInput | null,
  state?: ModelStringInput | null,
  country?: ModelStringInput | null,
  zip?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  address?: ModelStringInput | null,
  details?: ModelStringInput | null,
  and?: Array< ModelDeliveryConditionInput | null > | null,
  or?: Array< ModelDeliveryConditionInput | null > | null,
  not?: ModelDeliveryConditionInput | null,
  clientDeliveryAddressId?: ModelIDInput | null,
  deliveryOrderId?: ModelIDInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type UpdateDeliveryInput = {
  id: string,
  city?: string | null,
  state?: string | null,
  country?: string | null,
  zip?: string | null,
  phone?: string | null,
  address?: string | null,
  details?: string | null,
  clientDeliveryAddressId?: string | null,
  deliveryOrderId?: string | null,
};

export type DeleteDeliveryInput = {
  id: string,
};

export type CreateProductInput = {
  id?: string | null,
  name: string,
  price: number,
  weight?: number | null,
  options: Array< ProductOptionsInput >,
  thumbnail: string,
  images: Array< string >,
  description: string,
  avilable: boolean,
  unlimited: boolean,
  extraDetails?: string | null,
};

export type ProductOptionsInput = {
  name: string,
  thumbnail: string,
  colorCode: string,
  stock: number,
};

export type ModelProductConditionInput = {
  name?: ModelStringInput | null,
  price?: ModelFloatInput | null,
  weight?: ModelFloatInput | null,
  thumbnail?: ModelStringInput | null,
  images?: ModelStringInput | null,
  description?: ModelStringInput | null,
  avilable?: ModelBooleanInput | null,
  unlimited?: ModelBooleanInput | null,
  extraDetails?: ModelStringInput | null,
  and?: Array< ModelProductConditionInput | null > | null,
  or?: Array< ModelProductConditionInput | null > | null,
  not?: ModelProductConditionInput | null,
};

export type ModelFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type UpdateProductInput = {
  id: string,
  name?: string | null,
  price?: number | null,
  weight?: number | null,
  options?: Array< ProductOptionsInput > | null,
  thumbnail?: string | null,
  images?: Array< string > | null,
  description?: string | null,
  avilable?: boolean | null,
  unlimited?: boolean | null,
  extraDetails?: string | null,
};

export type DeleteProductInput = {
  id: string,
};

export type CreateOrderInput = {
  id?: string | null,
  title: string,
  date: string,
  total: number,
  orderDetails: Array< OrderDetailInput >,
  status: OrderStatus,
  paymentStatus: PaymentStatus,
  paymentType: PaymentType,
  clientOrdersId?: string | null,
  orderDeliveryId?: string | null,
};

export type OrderDetailInput = {
  productID: string,
  productName: string,
  productColor: string,
  productThumbnail: string,
  quantity: number,
  total: number,
};

export type ModelOrderConditionInput = {
  title?: ModelStringInput | null,
  date?: ModelStringInput | null,
  total?: ModelFloatInput | null,
  status?: ModelOrderStatusInput | null,
  paymentStatus?: ModelPaymentStatusInput | null,
  paymentType?: ModelPaymentTypeInput | null,
  and?: Array< ModelOrderConditionInput | null > | null,
  or?: Array< ModelOrderConditionInput | null > | null,
  not?: ModelOrderConditionInput | null,
  clientOrdersId?: ModelIDInput | null,
  orderDeliveryId?: ModelIDInput | null,
};

export type ModelOrderStatusInput = {
  eq?: OrderStatus | null,
  ne?: OrderStatus | null,
};

export type ModelPaymentStatusInput = {
  eq?: PaymentStatus | null,
  ne?: PaymentStatus | null,
};

export type ModelPaymentTypeInput = {
  eq?: PaymentType | null,
  ne?: PaymentType | null,
};

export type UpdateOrderInput = {
  id: string,
  title?: string | null,
  date?: string | null,
  total?: number | null,
  orderDetails?: Array< OrderDetailInput > | null,
  status?: OrderStatus | null,
  paymentStatus?: PaymentStatus | null,
  paymentType?: PaymentType | null,
  clientOrdersId?: string | null,
  orderDeliveryId?: string | null,
};

export type DeleteOrderInput = {
  id: string,
};

export type CreateProductOrdersInput = {
  id?: string | null,
  productID: string,
  orderID: string,
};

export type ModelProductOrdersConditionInput = {
  productID?: ModelIDInput | null,
  orderID?: ModelIDInput | null,
  and?: Array< ModelProductOrdersConditionInput | null > | null,
  or?: Array< ModelProductOrdersConditionInput | null > | null,
  not?: ModelProductOrdersConditionInput | null,
};

export type UpdateProductOrdersInput = {
  id: string,
  productID?: string | null,
  orderID?: string | null,
};

export type DeleteProductOrdersInput = {
  id: string,
};

export type ModelClientFilterInput = {
  id?: ModelIDInput | null,
  user?: ModelStringInput | null,
  name?: ModelStringInput | null,
  lastname?: ModelStringInput | null,
  city?: ModelStringInput | null,
  state?: ModelStringInput | null,
  country?: ModelStringInput | null,
  zip?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  and?: Array< ModelClientFilterInput | null > | null,
  or?: Array< ModelClientFilterInput | null > | null,
  not?: ModelClientFilterInput | null,
};

export type ModelClientConnection = {
  __typename: "ModelClientConnection",
  items:  Array<Client | null >,
  nextToken?: string | null,
};

export type ModelDeliveryFilterInput = {
  id?: ModelIDInput | null,
  city?: ModelStringInput | null,
  state?: ModelStringInput | null,
  country?: ModelStringInput | null,
  zip?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  address?: ModelStringInput | null,
  details?: ModelStringInput | null,
  and?: Array< ModelDeliveryFilterInput | null > | null,
  or?: Array< ModelDeliveryFilterInput | null > | null,
  not?: ModelDeliveryFilterInput | null,
  clientDeliveryAddressId?: ModelIDInput | null,
  deliveryOrderId?: ModelIDInput | null,
};

export type ModelOrderFilterInput = {
  id?: ModelIDInput | null,
  title?: ModelStringInput | null,
  date?: ModelStringInput | null,
  total?: ModelFloatInput | null,
  status?: ModelOrderStatusInput | null,
  paymentStatus?: ModelPaymentStatusInput | null,
  paymentType?: ModelPaymentTypeInput | null,
  and?: Array< ModelOrderFilterInput | null > | null,
  or?: Array< ModelOrderFilterInput | null > | null,
  not?: ModelOrderFilterInput | null,
  clientOrdersId?: ModelIDInput | null,
  orderDeliveryId?: ModelIDInput | null,
};

export type ModelProductFilterInput = {
  id?: ModelIDInput | null,
  name?: ModelStringInput | null,
  price?: ModelFloatInput | null,
  weight?: ModelFloatInput | null,
  thumbnail?: ModelStringInput | null,
  images?: ModelStringInput | null,
  description?: ModelStringInput | null,
  avilable?: ModelBooleanInput | null,
  unlimited?: ModelBooleanInput | null,
  extraDetails?: ModelStringInput | null,
  and?: Array< ModelProductFilterInput | null > | null,
  or?: Array< ModelProductFilterInput | null > | null,
  not?: ModelProductFilterInput | null,
};

export type ModelProductConnection = {
  __typename: "ModelProductConnection",
  items:  Array<Product | null >,
  nextToken?: string | null,
};

export type ModelProductOrdersFilterInput = {
  id?: ModelIDInput | null,
  productID?: ModelIDInput | null,
  orderID?: ModelIDInput | null,
  and?: Array< ModelProductOrdersFilterInput | null > | null,
  or?: Array< ModelProductOrdersFilterInput | null > | null,
  not?: ModelProductOrdersFilterInput | null,
};

export type CreateClientMutationVariables = {
  input: CreateClientInput,
  condition?: ModelClientConditionInput | null,
};

export type CreateClientMutation = {
  createClient?:  {
    __typename: "Client",
    id: string,
    user: string,
    name: string,
    lastname: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    email: string,
    deliveryAddress?:  {
      __typename: "ModelDeliveryConnection",
      items:  Array< {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    orders?:  {
      __typename: "ModelOrderConnection",
      items:  Array< {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type UpdateClientMutationVariables = {
  input: UpdateClientInput,
  condition?: ModelClientConditionInput | null,
};

export type UpdateClientMutation = {
  updateClient?:  {
    __typename: "Client",
    id: string,
    user: string,
    name: string,
    lastname: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    email: string,
    deliveryAddress?:  {
      __typename: "ModelDeliveryConnection",
      items:  Array< {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    orders?:  {
      __typename: "ModelOrderConnection",
      items:  Array< {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type DeleteClientMutationVariables = {
  input: DeleteClientInput,
  condition?: ModelClientConditionInput | null,
};

export type DeleteClientMutation = {
  deleteClient?:  {
    __typename: "Client",
    id: string,
    user: string,
    name: string,
    lastname: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    email: string,
    deliveryAddress?:  {
      __typename: "ModelDeliveryConnection",
      items:  Array< {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    orders?:  {
      __typename: "ModelOrderConnection",
      items:  Array< {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type CreateDeliveryMutationVariables = {
  input: CreateDeliveryInput,
  condition?: ModelDeliveryConditionInput | null,
};

export type CreateDeliveryMutation = {
  createDelivery?:  {
    __typename: "Delivery",
    id: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    address: string,
    details?: string | null,
    order?:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    } | null,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientDeliveryAddressId?: string | null,
    deliveryOrderId?: string | null,
    owner?: string | null,
  } | null,
};

export type UpdateDeliveryMutationVariables = {
  input: UpdateDeliveryInput,
  condition?: ModelDeliveryConditionInput | null,
};

export type UpdateDeliveryMutation = {
  updateDelivery?:  {
    __typename: "Delivery",
    id: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    address: string,
    details?: string | null,
    order?:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    } | null,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientDeliveryAddressId?: string | null,
    deliveryOrderId?: string | null,
    owner?: string | null,
  } | null,
};

export type DeleteDeliveryMutationVariables = {
  input: DeleteDeliveryInput,
  condition?: ModelDeliveryConditionInput | null,
};

export type DeleteDeliveryMutation = {
  deleteDelivery?:  {
    __typename: "Delivery",
    id: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    address: string,
    details?: string | null,
    order?:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    } | null,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientDeliveryAddressId?: string | null,
    deliveryOrderId?: string | null,
    owner?: string | null,
  } | null,
};

export type CreateProductMutationVariables = {
  input: CreateProductInput,
  condition?: ModelProductConditionInput | null,
};

export type CreateProductMutation = {
  createProduct?:  {
    __typename: "Product",
    id: string,
    name: string,
    price: number,
    weight?: number | null,
    options:  Array< {
      __typename: "ProductOptions",
      name: string,
      thumbnail: string,
      colorCode: string,
      stock: number,
    } >,
    thumbnail: string,
    images: Array< string >,
    description: string,
    avilable: boolean,
    unlimited: boolean,
    extraDetails?: string | null,
    order?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type UpdateProductMutationVariables = {
  input: UpdateProductInput,
  condition?: ModelProductConditionInput | null,
};

export type UpdateProductMutation = {
  updateProduct?:  {
    __typename: "Product",
    id: string,
    name: string,
    price: number,
    weight?: number | null,
    options:  Array< {
      __typename: "ProductOptions",
      name: string,
      thumbnail: string,
      colorCode: string,
      stock: number,
    } >,
    thumbnail: string,
    images: Array< string >,
    description: string,
    avilable: boolean,
    unlimited: boolean,
    extraDetails?: string | null,
    order?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type DeleteProductMutationVariables = {
  input: DeleteProductInput,
  condition?: ModelProductConditionInput | null,
};

export type DeleteProductMutation = {
  deleteProduct?:  {
    __typename: "Product",
    id: string,
    name: string,
    price: number,
    weight?: number | null,
    options:  Array< {
      __typename: "ProductOptions",
      name: string,
      thumbnail: string,
      colorCode: string,
      stock: number,
    } >,
    thumbnail: string,
    images: Array< string >,
    description: string,
    avilable: boolean,
    unlimited: boolean,
    extraDetails?: string | null,
    order?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type CreateOrderMutationVariables = {
  input: CreateOrderInput,
  condition?: ModelOrderConditionInput | null,
};

export type CreateOrderMutation = {
  createOrder?:  {
    __typename: "Order",
    id: string,
    title: string,
    date: string,
    total: number,
    orderDetails:  Array< {
      __typename: "OrderDetail",
      productID: string,
      productName: string,
      productColor: string,
      productThumbnail: string,
      quantity: number,
      total: number,
    } >,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    delivery?:  {
      __typename: "Delivery",
      id: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      address: string,
      details?: string | null,
      order?:  {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientDeliveryAddressId?: string | null,
      deliveryOrderId?: string | null,
      owner?: string | null,
    } | null,
    status: OrderStatus,
    paymentStatus: PaymentStatus,
    paymentType: PaymentType,
    products?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientOrdersId?: string | null,
    orderDeliveryId?: string | null,
    owner?: string | null,
  } | null,
};

export type UpdateOrderMutationVariables = {
  input: UpdateOrderInput,
  condition?: ModelOrderConditionInput | null,
};

export type UpdateOrderMutation = {
  updateOrder?:  {
    __typename: "Order",
    id: string,
    title: string,
    date: string,
    total: number,
    orderDetails:  Array< {
      __typename: "OrderDetail",
      productID: string,
      productName: string,
      productColor: string,
      productThumbnail: string,
      quantity: number,
      total: number,
    } >,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    delivery?:  {
      __typename: "Delivery",
      id: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      address: string,
      details?: string | null,
      order?:  {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientDeliveryAddressId?: string | null,
      deliveryOrderId?: string | null,
      owner?: string | null,
    } | null,
    status: OrderStatus,
    paymentStatus: PaymentStatus,
    paymentType: PaymentType,
    products?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientOrdersId?: string | null,
    orderDeliveryId?: string | null,
    owner?: string | null,
  } | null,
};

export type DeleteOrderMutationVariables = {
  input: DeleteOrderInput,
  condition?: ModelOrderConditionInput | null,
};

export type DeleteOrderMutation = {
  deleteOrder?:  {
    __typename: "Order",
    id: string,
    title: string,
    date: string,
    total: number,
    orderDetails:  Array< {
      __typename: "OrderDetail",
      productID: string,
      productName: string,
      productColor: string,
      productThumbnail: string,
      quantity: number,
      total: number,
    } >,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    delivery?:  {
      __typename: "Delivery",
      id: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      address: string,
      details?: string | null,
      order?:  {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientDeliveryAddressId?: string | null,
      deliveryOrderId?: string | null,
      owner?: string | null,
    } | null,
    status: OrderStatus,
    paymentStatus: PaymentStatus,
    paymentType: PaymentType,
    products?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientOrdersId?: string | null,
    orderDeliveryId?: string | null,
    owner?: string | null,
  } | null,
};

export type CreateProductOrdersMutationVariables = {
  input: CreateProductOrdersInput,
  condition?: ModelProductOrdersConditionInput | null,
};

export type CreateProductOrdersMutation = {
  createProductOrders?:  {
    __typename: "ProductOrders",
    id: string,
    productID: string,
    orderID: string,
    product:  {
      __typename: "Product",
      id: string,
      name: string,
      price: number,
      weight?: number | null,
      options:  Array< {
        __typename: "ProductOptions",
        name: string,
        thumbnail: string,
        colorCode: string,
        stock: number,
      } >,
      thumbnail: string,
      images: Array< string >,
      description: string,
      avilable: boolean,
      unlimited: boolean,
      extraDetails?: string | null,
      order?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    },
    order:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    },
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type UpdateProductOrdersMutationVariables = {
  input: UpdateProductOrdersInput,
  condition?: ModelProductOrdersConditionInput | null,
};

export type UpdateProductOrdersMutation = {
  updateProductOrders?:  {
    __typename: "ProductOrders",
    id: string,
    productID: string,
    orderID: string,
    product:  {
      __typename: "Product",
      id: string,
      name: string,
      price: number,
      weight?: number | null,
      options:  Array< {
        __typename: "ProductOptions",
        name: string,
        thumbnail: string,
        colorCode: string,
        stock: number,
      } >,
      thumbnail: string,
      images: Array< string >,
      description: string,
      avilable: boolean,
      unlimited: boolean,
      extraDetails?: string | null,
      order?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    },
    order:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    },
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type DeleteProductOrdersMutationVariables = {
  input: DeleteProductOrdersInput,
  condition?: ModelProductOrdersConditionInput | null,
};

export type DeleteProductOrdersMutation = {
  deleteProductOrders?:  {
    __typename: "ProductOrders",
    id: string,
    productID: string,
    orderID: string,
    product:  {
      __typename: "Product",
      id: string,
      name: string,
      price: number,
      weight?: number | null,
      options:  Array< {
        __typename: "ProductOptions",
        name: string,
        thumbnail: string,
        colorCode: string,
        stock: number,
      } >,
      thumbnail: string,
      images: Array< string >,
      description: string,
      avilable: boolean,
      unlimited: boolean,
      extraDetails?: string | null,
      order?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    },
    order:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    },
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type GetClientQueryVariables = {
  id: string,
};

export type GetClientQuery = {
  getClient?:  {
    __typename: "Client",
    id: string,
    user: string,
    name: string,
    lastname: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    email: string,
    deliveryAddress?:  {
      __typename: "ModelDeliveryConnection",
      items:  Array< {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    orders?:  {
      __typename: "ModelOrderConnection",
      items:  Array< {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type ListClientsQueryVariables = {
  filter?: ModelClientFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListClientsQuery = {
  listClients?:  {
    __typename: "ModelClientConnection",
    items:  Array< {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetDeliveryQueryVariables = {
  id: string,
};

export type GetDeliveryQuery = {
  getDelivery?:  {
    __typename: "Delivery",
    id: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    address: string,
    details?: string | null,
    order?:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    } | null,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientDeliveryAddressId?: string | null,
    deliveryOrderId?: string | null,
    owner?: string | null,
  } | null,
};

export type ListDeliveriesQueryVariables = {
  filter?: ModelDeliveryFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListDeliveriesQuery = {
  listDeliveries?:  {
    __typename: "ModelDeliveryConnection",
    items:  Array< {
      __typename: "Delivery",
      id: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      address: string,
      details?: string | null,
      order?:  {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientDeliveryAddressId?: string | null,
      deliveryOrderId?: string | null,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetOrderQueryVariables = {
  id: string,
};

export type GetOrderQuery = {
  getOrder?:  {
    __typename: "Order",
    id: string,
    title: string,
    date: string,
    total: number,
    orderDetails:  Array< {
      __typename: "OrderDetail",
      productID: string,
      productName: string,
      productColor: string,
      productThumbnail: string,
      quantity: number,
      total: number,
    } >,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    delivery?:  {
      __typename: "Delivery",
      id: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      address: string,
      details?: string | null,
      order?:  {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientDeliveryAddressId?: string | null,
      deliveryOrderId?: string | null,
      owner?: string | null,
    } | null,
    status: OrderStatus,
    paymentStatus: PaymentStatus,
    paymentType: PaymentType,
    products?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientOrdersId?: string | null,
    orderDeliveryId?: string | null,
    owner?: string | null,
  } | null,
};

export type ListOrdersQueryVariables = {
  filter?: ModelOrderFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListOrdersQuery = {
  listOrders?:  {
    __typename: "ModelOrderConnection",
    items:  Array< {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetProductQueryVariables = {
  id: string,
};

export type GetProductQuery = {
  getProduct?:  {
    __typename: "Product",
    id: string,
    name: string,
    price: number,
    weight?: number | null,
    options:  Array< {
      __typename: "ProductOptions",
      name: string,
      thumbnail: string,
      colorCode: string,
      stock: number,
    } >,
    thumbnail: string,
    images: Array< string >,
    description: string,
    avilable: boolean,
    unlimited: boolean,
    extraDetails?: string | null,
    order?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type ListProductsQueryVariables = {
  filter?: ModelProductFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListProductsQuery = {
  listProducts?:  {
    __typename: "ModelProductConnection",
    items:  Array< {
      __typename: "Product",
      id: string,
      name: string,
      price: number,
      weight?: number | null,
      options:  Array< {
        __typename: "ProductOptions",
        name: string,
        thumbnail: string,
        colorCode: string,
        stock: number,
      } >,
      thumbnail: string,
      images: Array< string >,
      description: string,
      avilable: boolean,
      unlimited: boolean,
      extraDetails?: string | null,
      order?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetProductOrdersQueryVariables = {
  id: string,
};

export type GetProductOrdersQuery = {
  getProductOrders?:  {
    __typename: "ProductOrders",
    id: string,
    productID: string,
    orderID: string,
    product:  {
      __typename: "Product",
      id: string,
      name: string,
      price: number,
      weight?: number | null,
      options:  Array< {
        __typename: "ProductOptions",
        name: string,
        thumbnail: string,
        colorCode: string,
        stock: number,
      } >,
      thumbnail: string,
      images: Array< string >,
      description: string,
      avilable: boolean,
      unlimited: boolean,
      extraDetails?: string | null,
      order?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    },
    order:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    },
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type ListProductOrdersQueryVariables = {
  filter?: ModelProductOrdersFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListProductOrdersQuery = {
  listProductOrders?:  {
    __typename: "ModelProductOrdersConnection",
    items:  Array< {
      __typename: "ProductOrders",
      id: string,
      productID: string,
      orderID: string,
      product:  {
        __typename: "Product",
        id: string,
        name: string,
        price: number,
        weight?: number | null,
        thumbnail: string,
        images: Array< string >,
        description: string,
        avilable: boolean,
        unlimited: boolean,
        extraDetails?: string | null,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      },
      order:  {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      },
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type OnCreateClientSubscriptionVariables = {
  owner?: string | null,
};

export type OnCreateClientSubscription = {
  onCreateClient?:  {
    __typename: "Client",
    id: string,
    user: string,
    name: string,
    lastname: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    email: string,
    deliveryAddress?:  {
      __typename: "ModelDeliveryConnection",
      items:  Array< {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    orders?:  {
      __typename: "ModelOrderConnection",
      items:  Array< {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnUpdateClientSubscriptionVariables = {
  owner?: string | null,
};

export type OnUpdateClientSubscription = {
  onUpdateClient?:  {
    __typename: "Client",
    id: string,
    user: string,
    name: string,
    lastname: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    email: string,
    deliveryAddress?:  {
      __typename: "ModelDeliveryConnection",
      items:  Array< {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    orders?:  {
      __typename: "ModelOrderConnection",
      items:  Array< {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnDeleteClientSubscriptionVariables = {
  owner?: string | null,
};

export type OnDeleteClientSubscription = {
  onDeleteClient?:  {
    __typename: "Client",
    id: string,
    user: string,
    name: string,
    lastname: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    email: string,
    deliveryAddress?:  {
      __typename: "ModelDeliveryConnection",
      items:  Array< {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    orders?:  {
      __typename: "ModelOrderConnection",
      items:  Array< {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnCreateDeliverySubscriptionVariables = {
  owner?: string | null,
};

export type OnCreateDeliverySubscription = {
  onCreateDelivery?:  {
    __typename: "Delivery",
    id: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    address: string,
    details?: string | null,
    order?:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    } | null,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientDeliveryAddressId?: string | null,
    deliveryOrderId?: string | null,
    owner?: string | null,
  } | null,
};

export type OnUpdateDeliverySubscriptionVariables = {
  owner?: string | null,
};

export type OnUpdateDeliverySubscription = {
  onUpdateDelivery?:  {
    __typename: "Delivery",
    id: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    address: string,
    details?: string | null,
    order?:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    } | null,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientDeliveryAddressId?: string | null,
    deliveryOrderId?: string | null,
    owner?: string | null,
  } | null,
};

export type OnDeleteDeliverySubscriptionVariables = {
  owner?: string | null,
};

export type OnDeleteDeliverySubscription = {
  onDeleteDelivery?:  {
    __typename: "Delivery",
    id: string,
    city: string,
    state: string,
    country: string,
    zip: string,
    phone: string,
    address: string,
    details?: string | null,
    order?:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    } | null,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientDeliveryAddressId?: string | null,
    deliveryOrderId?: string | null,
    owner?: string | null,
  } | null,
};

export type OnCreateOrderSubscriptionVariables = {
  owner?: string | null,
};

export type OnCreateOrderSubscription = {
  onCreateOrder?:  {
    __typename: "Order",
    id: string,
    title: string,
    date: string,
    total: number,
    orderDetails:  Array< {
      __typename: "OrderDetail",
      productID: string,
      productName: string,
      productColor: string,
      productThumbnail: string,
      quantity: number,
      total: number,
    } >,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    delivery?:  {
      __typename: "Delivery",
      id: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      address: string,
      details?: string | null,
      order?:  {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientDeliveryAddressId?: string | null,
      deliveryOrderId?: string | null,
      owner?: string | null,
    } | null,
    status: OrderStatus,
    paymentStatus: PaymentStatus,
    paymentType: PaymentType,
    products?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientOrdersId?: string | null,
    orderDeliveryId?: string | null,
    owner?: string | null,
  } | null,
};

export type OnUpdateOrderSubscriptionVariables = {
  owner?: string | null,
};

export type OnUpdateOrderSubscription = {
  onUpdateOrder?:  {
    __typename: "Order",
    id: string,
    title: string,
    date: string,
    total: number,
    orderDetails:  Array< {
      __typename: "OrderDetail",
      productID: string,
      productName: string,
      productColor: string,
      productThumbnail: string,
      quantity: number,
      total: number,
    } >,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    delivery?:  {
      __typename: "Delivery",
      id: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      address: string,
      details?: string | null,
      order?:  {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientDeliveryAddressId?: string | null,
      deliveryOrderId?: string | null,
      owner?: string | null,
    } | null,
    status: OrderStatus,
    paymentStatus: PaymentStatus,
    paymentType: PaymentType,
    products?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientOrdersId?: string | null,
    orderDeliveryId?: string | null,
    owner?: string | null,
  } | null,
};

export type OnDeleteOrderSubscriptionVariables = {
  owner?: string | null,
};

export type OnDeleteOrderSubscription = {
  onDeleteOrder?:  {
    __typename: "Order",
    id: string,
    title: string,
    date: string,
    total: number,
    orderDetails:  Array< {
      __typename: "OrderDetail",
      productID: string,
      productName: string,
      productColor: string,
      productThumbnail: string,
      quantity: number,
      total: number,
    } >,
    client?:  {
      __typename: "Client",
      id: string,
      user: string,
      name: string,
      lastname: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      email: string,
      deliveryAddress?:  {
        __typename: "ModelDeliveryConnection",
        nextToken?: string | null,
      } | null,
      orders?:  {
        __typename: "ModelOrderConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    delivery?:  {
      __typename: "Delivery",
      id: string,
      city: string,
      state: string,
      country: string,
      zip: string,
      phone: string,
      address: string,
      details?: string | null,
      order?:  {
        __typename: "Order",
        id: string,
        title: string,
        date: string,
        total: number,
        status: OrderStatus,
        paymentStatus: PaymentStatus,
        paymentType: PaymentType,
        createdAt: string,
        updatedAt: string,
        clientOrdersId?: string | null,
        orderDeliveryId?: string | null,
        owner?: string | null,
      } | null,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientDeliveryAddressId?: string | null,
      deliveryOrderId?: string | null,
      owner?: string | null,
    } | null,
    status: OrderStatus,
    paymentStatus: PaymentStatus,
    paymentType: PaymentType,
    products?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    clientOrdersId?: string | null,
    orderDeliveryId?: string | null,
    owner?: string | null,
  } | null,
};

export type OnCreateProductSubscriptionVariables = {
  owner?: string | null,
};

export type OnCreateProductSubscription = {
  onCreateProduct?:  {
    __typename: "Product",
    id: string,
    name: string,
    price: number,
    weight?: number | null,
    options:  Array< {
      __typename: "ProductOptions",
      name: string,
      thumbnail: string,
      colorCode: string,
      stock: number,
    } >,
    thumbnail: string,
    images: Array< string >,
    description: string,
    avilable: boolean,
    unlimited: boolean,
    extraDetails?: string | null,
    order?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnUpdateProductSubscriptionVariables = {
  owner?: string | null,
};

export type OnUpdateProductSubscription = {
  onUpdateProduct?:  {
    __typename: "Product",
    id: string,
    name: string,
    price: number,
    weight?: number | null,
    options:  Array< {
      __typename: "ProductOptions",
      name: string,
      thumbnail: string,
      colorCode: string,
      stock: number,
    } >,
    thumbnail: string,
    images: Array< string >,
    description: string,
    avilable: boolean,
    unlimited: boolean,
    extraDetails?: string | null,
    order?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnDeleteProductSubscriptionVariables = {
  owner?: string | null,
};

export type OnDeleteProductSubscription = {
  onDeleteProduct?:  {
    __typename: "Product",
    id: string,
    name: string,
    price: number,
    weight?: number | null,
    options:  Array< {
      __typename: "ProductOptions",
      name: string,
      thumbnail: string,
      colorCode: string,
      stock: number,
    } >,
    thumbnail: string,
    images: Array< string >,
    description: string,
    avilable: boolean,
    unlimited: boolean,
    extraDetails?: string | null,
    order?:  {
      __typename: "ModelProductOrdersConnection",
      items:  Array< {
        __typename: "ProductOrders",
        id: string,
        productID: string,
        orderID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnCreateProductOrdersSubscriptionVariables = {
  owner?: string | null,
};

export type OnCreateProductOrdersSubscription = {
  onCreateProductOrders?:  {
    __typename: "ProductOrders",
    id: string,
    productID: string,
    orderID: string,
    product:  {
      __typename: "Product",
      id: string,
      name: string,
      price: number,
      weight?: number | null,
      options:  Array< {
        __typename: "ProductOptions",
        name: string,
        thumbnail: string,
        colorCode: string,
        stock: number,
      } >,
      thumbnail: string,
      images: Array< string >,
      description: string,
      avilable: boolean,
      unlimited: boolean,
      extraDetails?: string | null,
      order?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    },
    order:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    },
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnUpdateProductOrdersSubscriptionVariables = {
  owner?: string | null,
};

export type OnUpdateProductOrdersSubscription = {
  onUpdateProductOrders?:  {
    __typename: "ProductOrders",
    id: string,
    productID: string,
    orderID: string,
    product:  {
      __typename: "Product",
      id: string,
      name: string,
      price: number,
      weight?: number | null,
      options:  Array< {
        __typename: "ProductOptions",
        name: string,
        thumbnail: string,
        colorCode: string,
        stock: number,
      } >,
      thumbnail: string,
      images: Array< string >,
      description: string,
      avilable: boolean,
      unlimited: boolean,
      extraDetails?: string | null,
      order?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    },
    order:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    },
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnDeleteProductOrdersSubscriptionVariables = {
  owner?: string | null,
};

export type OnDeleteProductOrdersSubscription = {
  onDeleteProductOrders?:  {
    __typename: "ProductOrders",
    id: string,
    productID: string,
    orderID: string,
    product:  {
      __typename: "Product",
      id: string,
      name: string,
      price: number,
      weight?: number | null,
      options:  Array< {
        __typename: "ProductOptions",
        name: string,
        thumbnail: string,
        colorCode: string,
        stock: number,
      } >,
      thumbnail: string,
      images: Array< string >,
      description: string,
      avilable: boolean,
      unlimited: boolean,
      extraDetails?: string | null,
      order?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    },
    order:  {
      __typename: "Order",
      id: string,
      title: string,
      date: string,
      total: number,
      orderDetails:  Array< {
        __typename: "OrderDetail",
        productID: string,
        productName: string,
        productColor: string,
        productThumbnail: string,
        quantity: number,
        total: number,
      } >,
      client?:  {
        __typename: "Client",
        id: string,
        user: string,
        name: string,
        lastname: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        email: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      delivery?:  {
        __typename: "Delivery",
        id: string,
        city: string,
        state: string,
        country: string,
        zip: string,
        phone: string,
        address: string,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
        clientDeliveryAddressId?: string | null,
        deliveryOrderId?: string | null,
        owner?: string | null,
      } | null,
      status: OrderStatus,
      paymentStatus: PaymentStatus,
      paymentType: PaymentType,
      products?:  {
        __typename: "ModelProductOrdersConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      clientOrdersId?: string | null,
      orderDeliveryId?: string | null,
      owner?: string | null,
    },
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};
